In [3]:
import pandas as pd
import numpy as np

WORKING WITH JSON

pd.read_json('train.json')

In [7]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-25,1771977601,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-25,1771977601,0.0404
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-25,1771977601,0.6950
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-25,1771977601,0.8990
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-25,1771977601,4.1500
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-25,1771977601,2.6200
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-25,1771977601,0.1760
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-25,1771977601,0.2080
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-25,1771977601,0.2810
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-25,1771977601,0.2810

WORKING WITH SQL

In [10]:
!pip install mysql-connector

Requirement already satisfied: mysql-connector in c:\users\akshay\anaconda3\lib\site-packages (2.2.9)

In [11]:
import mysql.connector

In [14]:
conn = mysql.connector.connect(host='localhost', user='root',password='', database='world')

In [22]:
pd.read_sql_query("SELECT * FROM city WHERE CountryCode = 'IND' AND District = 'Maharashtra'", conn)

C:\Users\Akshay\AppData\Local\Temp\ipykernel_23176\887454777.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city WHERE CountryCode = 'IND' AND District = 'Maharashtra'", conn)

      ID                        Name CountryCode     District  Population
0   1024             Mumbai (Bombay)         IND  Maharashtra    10500000
1   1032                      Nagpur         IND  Maharashtra     1624752
2   1034                        Pune         IND  Maharashtra     1566651
3   1041                      Kalyan         IND  Maharashtra     1014557
4   1049               Thane (Thana)         IND  Maharashtra      803389
5   1059              Nashik (Nasik)         IND  Maharashtra      656925
6   1061          Solapur (Sholapur)         IND  Maharashtra      604215
7   1065  Shambajinagar (Aurangabad)         IND  Maharashtra      573272
8   1070            Pimpri-Chinchwad         IND  Maharashtra      517083
9   1083                    Amravati         IND  Maharashtra      421576
10  1087                    Kolhapur         IND  Maharashtra      406370
11  1093                    Bhiwandi         IND  Maharashtra      379070
12  1095                  Ulhasnagar         IND  Maharashtra      369077
13  1098                    Malegaon         IND  Maharashtra      342595
14  1101                       Akola         IND  Maharashtra      328034
15  1106                  New Bombay         IND  Maharashtra      307297
16  1113              Dhule (Dhulia)         IND  Maharashtra      278317
17  1115             Nanded (Nander)         IND  Maharashtra      275083
18  1125                     Jalgaon         IND  Maharashtra      242193
19  1136                  Chandrapur         IND  Maharashtra      226105
20  1144                Ichalkaranji         IND  Maharashtra      214950
21  1155                       Latur         IND  Maharashtra      197408
22  1158                      Sangli         IND  Maharashtra      193197
23  1159                    Parbhani         IND  Maharashtra      190255
24  1168                  Ahmadnagar         IND  Maharashtra      181339
25  1172              Mira Bhayandar         IND  Maharashtra      175372
26  1174                       Jalna         IND  Maharashtra      174985
27  1218                    Bhusawal         IND  Maharashtra      145143
28  1254                       Miraj         IND  Maharashtra      125407
29  1292                  Bhir (Bid)         IND  Maharashtra      112434
30  1298                     Gondiya         IND  Maharashtra      109470
31  1300          Yeotmal (Yavatmal)         IND  Maharashtra      108578
32  1320                      Wardha         IND  Maharashtra      102985
33  1344                    Achalpur         IND  Maharashtra       96216
34  1348                      Satara         IND  Maharashtra       95133